### ISSUE TITLE
any alternatives with up to date mpv version?

### ISSUE THREAD

**Issue by junguler** [qwerty12/mpv-winbuild#25]
hello, i've been on your last build of mpv with frei0r support for over 6 months now, are you aware of any other pc build that includes this filter? 

i wanted to thank you again for including it in the first place btw, it's been really helpful for preserving my sanity and eyesight when viewing overly bright content

**Comment by qwerty12** [comment]
Hi,

I'm sorry, I didn't have enough time to keep the build scripts etc. up to
date with the original projects, especially when I stopped using my PC to
primarily watch stuff - I still have the last build from here installed. I
have no idea of any other builds that include the filters, I've seen one
that has the LuaSocket changes from here, but not the frei0r stuff, sadly

**Comment by junguler** [comment]
thanks for getting back to me, there is nothing to be sorry about friend, i'm thankful to you for including these filters and understand why it was too much to keep things updated, especially when you didn't need it anymore

it's all good, thanks again
